### ISSUE TITLE
Current Volume catalog item not working

### ISSUE THREAD

**Issue by ueffel** [Fuhrmann/keypirinha-volumecontrol#1]
The "Current Volume" item does not allow me to enter the args-step so I can enter my desired volume.

Executing the "Current Volume" item produces an error:
```
20:22:08.308 ** ERROR: Error from VolumeControl.VolumeControl.on_execute: <class 'IndexError'>: list index out of range
Traceback (most recent call last):
  File "C:\Users\ueffel\AppData\Roaming\Keypirinha\InstalledPackages\VolumeControl.keypirinha-package\volumecontrol.py", line 66, in on_execute
```
I'm using Keypirinha 2.21. There was a change with the args_hint of items, see [here](https://github.com/Keypirinha/Keypirinha/issues/328).

**Comment by Fuhrmann** [comment]
Hey @ueffel.

The "Current Volume" suggestion doesnt not have any purpose than to just show the current volume level. 

If you press tab it should not do anything, neither if you press enter.

If you want to change the volume you have to type something like:

"vol 52" than this will appear:

![image](https://user-images.githubusercontent.com/1160365/47522441-96503180-d863-11e8-96c2-d259013f9e64.png)

About the error you are getting I forget to handle that. I'll make the changes and update.

If you have any suggestions please tell me.

**Comment by ueffel** [comment]
Alright I didn't watch the complete-usage-gif right.
Well maybe the item can work as I thought initially.
Suggest "Current Volume" with args_hint=required and in the args step, accept a number to set the volume.

**Comment by Fuhrmann** [comment]
I'll close this issue since the problem doesn't exists, but your suggestion is more then welcoming.
